[package]
name = "vanillavillage"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/dylanopen/vanillavillage"
authors = ["dylancode <opendylan@proton.me"]
categories = ["game", "simulation", "graphics"]
keywords = ["game", "simulation", "build", "town", "city"]
description = "Build a village and keep your villagers happy in this indie town-builder adventure game"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"

[dependencies.bevy]
version = "0.17.3"
default-features = true

[dependencies.tracing]
version = "0.1.43"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.22"
default-features = false

#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]

#[target.x86_64-pc-windows-msvc]
#linker = "rust-lld.exe"

